apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eventbus-default-js
  namespace: argo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      controller: eventbus-controller
      eventbus-name: default
      owner-name: default
