apiVersion: v1
kind: PersistentVolume
metadata:
  name: pxe-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.5.240
    path: /Container/pxe
  claimRef:
    namespace: argo
    name: pxe-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pxe-nfs
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pxe-nfs
  resources:
    requests:
      storage: 1Gi
