apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  description: Secret management and security scanning
  sourceRepos:
    - https://charts.external-secrets.io
    - https://1password.github.io/connect-helm-charts
    - https://oauth2-proxy.github.io/manifests
    - https://aquasecurity.github.io/helm-charts
    - https://kyverno.github.io/kyverno/
    - https://github.com/Tsuguya/home-cluster.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: CustomResourceDefinition
    - group: '*'
      kind: ClusterRole
    - group: '*'
      kind: ClusterRoleBinding
    - group: ''
      kind: Namespace
    - group: aquasecurity.github.io
      kind: '*'
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: external-secrets.io
      kind: ClusterExternalSecret
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: kyverno.io
      kind: '*'
