apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rss-pg
  namespace: rss
spec:
  instances: 1
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 512Mi
  affinity:
    nodeSelector:
      kubernetes.io/hostname: wn-01
  storage:
    storageClass: qnap-iscsi
    size: 5Gi
  bootstrap:
    initdb:
      database: rssreader
      owner: rss
      secret:
        name: rss-pg-credentials
