apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: rss-ui
  namespace: rss
spec:
  image: ghcr.io/tsuguya/home-rss-ui:v0.0.2
  replicas: 1
  executor: containerd-shim-spin
  imagePullSecrets:
    - name: ghcr-pull
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
