apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: rss-fetcher
  namespace: rss
spec:
  image: ghcr.io/tsuguya/home-rss-fetcher:v0.0.2
  replicas: 1
  executor: containerd-shim-spin
  imagePullSecrets:
    - name: ghcr-pull
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
  variables:
    - name: db_url
      valueFrom:
        secretKeyRef:
          name: rss-pg-credentials
          key: uri
