apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: harbor-trivy
  namespace: harbor
spec:
  endpointSelector:
    matchLabels:
      app: harbor
      component: trivy
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: harbor
            component: core
        - matchLabels:
            app: harbor
            component: jobservice
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: prometheus
            io.kubernetes.pod.namespace: monitoring
      toPorts:
        - ports:
            - port: "8001"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app: harbor
            component: redis
      toPorts:
        - ports:
            - port: "6379"
              protocol: TCP
    - toFQDNs:
        - matchName: "ghcr.io"
        - matchPattern: "*.githubusercontent.com"
        - matchName: "registry.infra.tgy.io"
        - matchName: "mirror.gcr.io"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
