expose:
  type: clusterIP
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  clusterIP:
    name: harbor
    staticClusterIP: "10.107.133.63"

updateStrategy:
  type: Recreate

externalURL: https://registry.infra.tgy.io

caBundleSecretName: pg-ca-cert

existingSecretAdminPassword: harbor-admin-credentials
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
existingSecretSecretKey: harbor-core-secret

database:
  type: external
  external:
    host: shared-pg-rw.database.svc
    port: "5432"
    username: harbor
    coreDatabase: harbor
    existingSecret: harbor-pg-credentials
    sslmode: verify-full

redis:
  type: internal

persistence:
  enabled: true
  imageChartStorage:
    type: s3
    s3:
      region: us-east-1
      bucket: harbor
      regionendpoint: http://seaweedfs-filer.seaweedfs.svc:8333
      secure: false
      v4auth: true
      existingSecret: harbor-s3-credentials
    disableredirect: true
  persistentVolumeClaim:
    registry:
      storageClass: "-"
    jobservice:
      jobLog:
        storageClass: "-"

trivy:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 1Gi

core:
  extraEnvVars:
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: harbor-kanidm-oauth
          key: clientSecret
    - name: CONFIG_OVERWRITE_JSON
      value: '{"auth_mode":"oidc_auth","oidc_name":"Kanidm","oidc_endpoint":"https://idm.tgy.io/oauth2/openid/harbor","oidc_client_id":"harbor","oidc_client_secret":"$(OIDC_CLIENT_SECRET)","oidc_scope":"openid,profile,email","oidc_verify_cert":"true","oidc_auto_onboard":"true","oidc_user_claim":"preferred_username"}'
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

portal:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

registry:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 512Mi

jobservice:
  jobLoggers:
    - database
  loggerSweeperDuration: 14
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 256Mi

nginx:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

exporter:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack
