apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qdrant
  namespace: argocd
spec:
  project: ai
  sources:
    - repoURL: https://qdrant.github.io/qdrant-helm
      chart: qdrant
      targetRevision: "1.17.1"
      helm:
        releaseName: qdrant
        valueFiles:
          - $values/helm-values/qdrant/values.yaml
    - repoURL: https://github.com/Tsuguya/home-cluster.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: qdrant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
