apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qnap-csi
  namespace: argocd
spec:
  project: storage
  sources:
    - repoURL: https://github.com/Tsuguya/home-cluster.git
      targetRevision: main
      path: kustomize/qnap-csi
    - repoURL: https://github.com/Tsuguya/home-cluster.git
      targetRevision: main
      path: manifests/trident
    - repoURL: https://github.com/Tsuguya/home-cluster.git
      targetRevision: main
      path: manifests/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: trident
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
