apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spin-operator
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: ghcr.io/spinframework/charts
      chart: spin-operator
      targetRevision: "0.6.1"
      helm:
        releaseName: spin-operator
        valueFiles:
          - $values/helm-values/spin-operator/values.yaml
    - repoURL: https://github.com/Tsuguya/home-cluster.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Tsuguya/home-cluster.git
      targetRevision: main
      path: manifests/spin-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: spin-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
