apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-notifications-secret
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: argocd-notifications-secret
