apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: images-github-webhook
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: images-github-webhook
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: images-github-webhook
        metadataPolicy: None
