apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talosconfig
  namespace: argo
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talosconfig
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: talosconfig
        metadataPolicy: None
