apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflared-tunnel-token
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: cloudflared-tunnel-token
