apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talosconfig
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talosconfig
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: talosconfig
