apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-pluto-fix
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pat-pluto-fix
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: github-pat-pluto-fix
