apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tofu-credentials
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-tofu-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare-tofu-credentials
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-tofu
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pat-tofu
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: github-pat-tofu
