apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-argo-workflows-oauth
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kanidm-argo-workflows-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: kanidm-argo-workflows-oauth
        metadataPolicy: None
