apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-harbor-robot
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: renovate-harbor-robot
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-robot-renovate
        metadataPolicy: None
        nullBytePolicy: Ignore
