apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-backup-credentials
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: r2-backup-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: r2-backup-credentials
        metadataPolicy: None
