apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age-key
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sops-age-key
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: sops-age-key
