apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-custom-build-github-webhook
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talos-custom-build-github-webhook
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: talos-custom-build-github-webhook
