apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-pg-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-pg-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: nextcloud-pg-credentials
