apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-backup-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: r2-backup-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: r2-backup-credentials
