apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-pg-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seaweedfs-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: seaweedfs-pg-credentials
        metadataPolicy: None
