apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: discord-webhook-argo
spec:
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - argo
          - talos-build
          - image-build
          - claude-code
          - horenso
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword
    target:
      name: discord-webhook-argo
      creationPolicy: Owner
      deletionPolicy: Retain
    dataFrom:
      - extract:
          conversionStrategy: Default
          decodingStrategy: None
          key: discord-webhook-argo
          metadataPolicy: None
