apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-s3-credentials
  namespace: harbor
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-s3-credentials
        metadataPolicy: None
