apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-core-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-core-secret
        metadataPolicy: None
