apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-core-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: harbor-core-secret
