apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-kanidm-oauth
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-kanidm-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: harbor-kanidm-oauth
