apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-credentials
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-admin-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: harbor-admin-credentials
