apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: horenso-pg-credentials
  namespace: horenso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: horenso-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: Horenso PostgreSQL
        metadataPolicy: None
