apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-robot-images
  namespace: image-build
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-robot-images
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: harbor-robot-images
        metadataPolicy: None
