apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosign-signing-key
  namespace: image-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cosign-signing-key
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: cosign.key
      remoteRef:
        key: cosign-signing-key
        property: private-key
    - secretKey: cosign.pub
      remoteRef:
        key: cosign-signing-key
        property: public-key
