apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-images
  namespace: image-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pat-images
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: github-pat-images
