apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-images
  namespace: image-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pat-images
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-pat-images
        metadataPolicy: None
