apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-pull-credentials
  namespace: image-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dockerhub-pull-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dockerhub-pull-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dockerhub-pull-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
