apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanidm-grafana-oauth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kanidm-grafana-oauth
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: kanidm-grafana-oauth
