apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-alertmanager
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discord-webhook-alertmanager
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: discord-webhook-alertmanager
        metadataPolicy: None
