apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-alertmanager-critical
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: discord-webhook-alertmanager-critical
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: discord-webhook-alerts-critical
        metadataPolicy: None
        property: webhook_url
