apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-pg-credentials
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: Grafana PostgreSQL
        metadataPolicy: None
