apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-kanidm-oauth
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-kanidm-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kanidm-nextcloud-oauth
