apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-pg-credentials
  namespace: nextcloud
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: nextcloud-pg-credentials
        metadataPolicy: None
