apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-admin-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: nextcloud-admin-credentials
