apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rss-pg-credentials
  namespace: rss
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rss-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      mergePolicy: Merge
      data:
        uri: "postgresql://{{ .username }}:{{ .password }}@rss-pg-rw.rss.svc.cluster.local:5432/rssreader?sslmode=require"
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: RSS PostgreSQL
        metadataPolicy: None
