apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rss-pg-credentials
  namespace: rss
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rss-pg-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: RSS PostgreSQL
        metadataPolicy: None
