apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-storage
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: loki-storage
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: seaweedfs-loki-s3
        metadataPolicy: None
