apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-artifacts
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argo-artifacts
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: seaweedfs-argo-s3
