apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-artifacts
  namespace: talos-build
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argo-artifacts
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: seaweedfs-argo-s3
        metadataPolicy: None
