apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-talos-build
  namespace: talos-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pat-talos-build
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: github-pat-talos-build
