apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub-pull-credentials
  namespace: talos-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dockerhub-pull-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"https://index.docker.io/v1/":{"auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dockerhub-pull-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dockerhub-pull-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
