apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pat
  namespace: talos-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ghcr-pat
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: github-pat-talos-build
        property: credential
