apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pat-talos-build
  namespace: talos-build
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-pat-talos-build
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: github-pat-talos-build
        metadataPolicy: None
