apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secureboot-signing-keys
  namespace: talos-build
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: secureboot-signing-keys
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: PK.auth
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secureboot-signing-keys
        property: PK-auth
        metadataPolicy: None
    - secretKey: KEK.auth
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secureboot-signing-keys
        property: KEK-auth
        metadataPolicy: None
    - secretKey: db.auth
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secureboot-signing-keys
        property: db-auth
        metadataPolicy: None
    - secretKey: pcr-signing-key.pem
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secureboot-signing-keys
        property: pcr-signing-key-pem
        metadataPolicy: None
    - secretKey: uki-signing-cert.pem
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secureboot-signing-keys
        property: uki-signing-cert-pem
        metadataPolicy: None
    - secretKey: uki-signing-key.pem
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: secureboot-signing-keys
        property: uki-signing-key-pem
        metadataPolicy: None
