apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qnap-backend-secret
  namespace: trident
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: qnap-backend-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: qnap-backend-secret
